// <auto-generated />
using System;
using ErosTTS.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErosTTS.Bot.Data.Migrations
{
    [DbContext(typeof(ErosTtsDbContext))]
    [Migration("20260205205414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.ConversationMessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("ConversationMessages", (string)null);
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.GuildCharacterStateEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("GuildCharacterStates", (string)null);
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.GuildTtsConfigurationEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TextChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("VoiceChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigurations", (string)null);
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.ConversationMessageEntity", b =>
                {
                    b.HasOne("ErosTTS.Bot.Data.Entities.GuildCharacterStateEntity", "GuildCharacterState")
                        .WithMany("ConversationHistory")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildCharacterState");
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.GuildCharacterStateEntity", b =>
                {
                    b.Navigation("ConversationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
