// <auto-generated />
using System;
using ErosTTS.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErosTTS.Bot.Data.Migrations
{
    [DbContext(typeof(ErosTtsDbContext))]
    [Migration("20260211211208_AddTtsProvider")]
    partial class AddTtsProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.GuildNpcSettingsEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveNpcId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSwitchEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SharedHistory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.HasIndex("ActiveNpcId");

                    b.ToTable("GuildNpcSettings", (string)null);
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.GuildTtsConfigurationEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TextChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TtsProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("VoiceChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigurations", (string)null);
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.NpcConversationMessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NpcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NpcName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("NpcId");

                    b.ToTable("NpcConversationMessages", (string)null);
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.NpcEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.ToTable("Npcs", (string)null);
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.GuildNpcSettingsEntity", b =>
                {
                    b.HasOne("ErosTTS.Bot.Data.Entities.NpcEntity", "ActiveNpc")
                        .WithMany()
                        .HasForeignKey("ActiveNpcId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveNpc");
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.NpcConversationMessageEntity", b =>
                {
                    b.HasOne("ErosTTS.Bot.Data.Entities.NpcEntity", "Npc")
                        .WithMany("ConversationMessages")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("ErosTTS.Bot.Data.Entities.NpcEntity", b =>
                {
                    b.Navigation("ConversationMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
